/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void quoteTest() throws IOException {
        Gson gson=new Gson();
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("quotes.json");
        Reader read= new InputStreamReader(is);
        List<Quotes> quoteList=gson.fromJson(read,new TypeToken<List<Quotes>>() {}.getType());
        int randomIndex = (int)Math.floor(Math.random()*(quoteList.size()+1));
        read.close();
        Quotes quotesObj=quoteList.get(randomIndex);
        assertNotNull(quotesObj);
    }
    @Test void quoteAPITest() throws IOException {
        assertNotNull(App.getQuoteAPI());
    }
}
