/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
//        System.out.println(new App().getGreeting());
        Quotes newQuotes=new Quotes("Marilyn Monroe","I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.");
        Gson gson=new Gson();
        String qJSON = gson.toJson(newQuotes);
        System.out.println(qJSON);

        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("quotes.json");
        Reader read= new InputStreamReader(is);
        List<Quotes> quoteList=gson.fromJson(read,new TypeToken<List<Quotes>>() {}.getType());
        int randomIndex = (int)Math.floor(Math.random()*(quoteList.size()+1));
        read.close();
        Quotes quotesObj=quoteList.get(randomIndex);
        System.out.println(quotesObj);

    }
}
